---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos72
    driver:
      image: centos:7.2.1511
      platform: rhel
      chef_version: latest
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which net-tools

suites:
  - name: default
    run_list:
      - recipe[nginx_inspec::default]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/tests-nginx-hardening
    attributes:
