---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: centos73
    driver:
      image: centos:7.3.1611
  - name: ubuntu1604
    driver:
      image: ubuntu:16.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
    attributes:
